[theme]

primaryColor="#205C2E"              # evergreen green
#backgroundColor="#205C2E"           # dark background
#secondaryBackgroundColor="#C7DAB1"  # card/sidebar background
#textColor="#000000"
font="acumen"

[server]
enableStaticServing = true